// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the current platform.
///
/// ── IMPORTANT ───────────────────────────────────────────────────────────────
/// This file is normally GENERATED by the FlutterFire CLI. Run:
///
///     dart pub global activate flutterfire_cli
///     flutterfire configure --project=<your-firebase-project-id>
///
/// which will overwrite this file with the real API keys/app ids for each
/// platform and drop the `google-services.json` / `GoogleService-Info.plist`
/// files in place.
///
/// The values below are intentionally left as clearly-marked placeholders so
/// the project compiles, while failing fast at runtime if you forget to run
/// `flutterfire configure`. Firebase API keys are NOT secrets (they identify,
/// not authenticate, the project) but they ARE project-specific, so they must
/// come from your own Firebase project.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Trusty currently targets Android, iOS and Web. Run '
          '`flutterfire configure` to add support for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ANDROID_API_KEY',
    appId: 'REPLACE_WITH_ANDROID_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'trusty-app',
    storageBucket: 'trusty-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'trusty-app',
    storageBucket: 'trusty-app.appspot.com',
    iosBundleId: 'app.trusty.trusty',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: 'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'trusty-app',
    authDomain: 'trusty-app.firebaseapp.com',
    storageBucket: 'trusty-app.appspot.com',
  );
}
